services:
  db:
    image: postgres:alpine
    container_name: snippet-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  snippet-service:
    build: .
    container_name: snippet-service
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db
      - asset-service
#      - printscript-service

    environment:
      BUCKET_URL: ${BUCKET_URL}
#      PRINTSCRIPT_URL: http://printscript-service:8080/validate
    networks:
      - snippet-net

  asset-service:
    container_name: "asset_service"
    image: "ghcr.io/austral-ingsis/snippet-asset-service:latest"
    ports:
      - "${ASSET_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_NAME: ${SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_NAME}
      SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_KEY: ${SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_KEY}
      SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT: ${SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

#  printscript-service:
#    image: ghcr.io/austral-ingsis/printscript-service:main.17
#    container_name: printscript-service
#    ports:
#      - "${PRINTSCRIPT_PORT}:8080"
#    networks:
#      - snippet-net

volumes:
  db:
  blob:


networks:
  snippet-net:
    external: true