services:
  snippet-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: snippet-service
    ports:
      - "${API_PORT}:8081"
    env_file:
      - .env
    networks:
      - snippet-net

volumes:
  db:
  blob:
  redis-data:

networks:
  snippet-net:
    external: true