services:
  db:
    image: postgres:alpine
    container_name: snippet-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: "snippet_redis"
    ports:
      - "6379:6379"

  snippet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snippet-service
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db
      - asset-service
      - redis
    environment:
      BUCKET_URL: ${BUCKET_URL}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  asset-service:
    container_name: "asset_service"
    image: "ghcr.io/austral-ingsis/snippet-asset-service:latest"
    ports:
      - "${ASSET_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_NAME: ${SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_NAME}
      SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_KEY: ${SPRING_CLOUD_AZURE_STORAGE_ACCOUNT_KEY}
      SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT: ${SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace
volumes:
  db:
  blob: