name: Build & Push Test Image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  call-deploy-workflow:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/deploy.yaml@main
    with:
      java-version: "21"
      environment: "development"
      service_name: "permission"
      image_route: "ghcr.io/ingsisprintscript/permission-service:dev"
    secrets: inherit